### ISSUE TITLE
Question about [epoch1] and [epoch2]

### ISSUE THREAD

**Issue by GhostCai** [arthur-qiu/ReliTalk#5]
Hi, thank you for your excellent work! I would like to know what [epoch1] and [epoch2] mean in the command you provide. Are they the same as the default values (120 and 10) in exp_runner.py and exp_runner_relight.py? I appreciate your clarification.

**Comment by arthur-qiu** [comment]
Default values are set for the given sample (https://github.com/arthur-qiu/ReliTalk/tree/main/data/datasets/Obama). When you use other videos, adjust it according to the video length, i.e., more epochs for shorter videos.

**Comment by GhostCai** [comment]
Thanks!!
